export const UI_TEXT = {
  action: 'Acci\u00f3n',
  assetSingular: 'Activo fijo',
  assetPlural: 'Activos fijos',
  clear: 'Limpiar',
  catalog: 'Cat\u00e1logo',
  catalogAvailable: 'Cat\u00e1logo disponible',
  catalogBaseSn: 'Cat\u00e1logo base SN',
  catalogHidden: 'Cat\u00e1logo oculto. Usa "Mostrar cat\u00e1logo" para ver los \u00edtems.',
  catalogManual: 'Sin cat\u00e1logo (manual)',
  catalogStandard: 'Cat\u00e1logo est\u00e1ndar',
  close: 'Cerrar',
  closeSession: 'Cerrar sesi\u00f3n',
  code: 'C\u00f3digo',
  codeInternal: 'C\u00f3digo interno',
  copyCode: 'Copiar c\u00f3digo',
  discard: 'Descartar',
  errors: 'Errores',
  hideCatalog: 'Ocultar cat\u00e1logo',
  institution: 'Instituci\u00f3n',
  institutionOptional: 'Instituci\u00f3n (opcional)',
  itemSingular: '\u00edtem',
  itemPlural: '\u00edtems',
  loading: 'Cargando...',
  next: 'Siguiente',
  noHistory: 'Sin historial.',
  noteShort: 'Observaci\u00f3n breve',
  page: 'P\u00e1gina',
  previous: 'Anterior',
  save: 'Guardar',
  saveChanges: 'Guardar cambios',
  saveKey: 'Guardar clave',
  savePhoto: 'Guardar foto',
  saving: 'Guardando...',
  search: 'B\u00fasqueda',
  searchAction: 'Buscar',
  session: 'Sesi\u00f3n',
  showCatalog: 'Mostrar cat\u00e1logo',
  updating: 'Actualizar',
}
